/**
 * Fixtures shaped like the real payloads, including their hostile cases.
 *
 * The crop name below is what a row looks like when someone has typed markup
 * into a free-text field. It is here, not in one test, so every rendering test
 * exercises it.
 */
import type {
  Decision,
  Field,
  IrrigationRecommendation,
  Shipment,
  ShipmentRisk,
} from '@/lib/types'

export const HOSTILE_NAME = '<img src=x onerror="alert(1)">Tomate cerise'

export const decision: Decision = {
  domain: 'IRRIGATION',
  domain_label_fr: 'Irrigation',
  subject_id: 'P03',
  subject_label_fr: 'Verger agrumes Est',
  headline_fr: 'Irrigation recommandée : 84 m³ sur 2 h 10.',
  outcome_code: 'IRRIGATE',
  inputs: [
    {
      key: 'soil_moisture',
      label_fr: 'Humidité du sol',
      value: 18.4,
      unit: '%',
      state: 'SIMULATED',
      state_label_fr: 'Simulé',
      origin: 'SEED_DEMO',
      origin_label_fr: 'Jeu de démonstration',
      source_label_fr: 'Démonstration',
      missing_reason_fr: null,
    },
    {
      key: 'water_tariff',
      label_fr: 'Tarif de l’eau',
      value: null,
      unit: 'MAD/m³',
      state: 'OBSERVED',
      state_label_fr: 'Observé',
      origin: 'MANUAL_ENTRY',
      origin_label_fr: 'Saisie manuelle',
      source_label_fr: null,
      missing_reason_fr: 'Aucun tarif de l’eau n’est renseigné pour cette parcelle.',
    },
  ],
  calculation_steps_fr: [
    '1. ET0 = 5,83 mm/j par FAO-56 Penman-Monteith (FAO-56 éq. 6).',
    '2. ETc = ET0 × Kc = 5,83 × 0,70 = 4,08 mm/j (FAO-56 éq. 31).',
  ],
  assumptions_fr: ['Culture : Agrumes. Sol : Limon.'],
  evidence: [
    {
      label_fr: 'Météo du jour',
      detail_fr: '32,0 / 18,0 °C, source Fournisseur hors ligne.',
      state: 'SIMULATED',
      state_label_fr: 'Simulé',
      source_label_fr: 'Fournisseur hors ligne',
      observed_at: null,
    },
  ],
  tradeoffs_fr: [],
  warnings_fr: ['La vitesse d’infiltration de ce sol n’est pas documentée.'],
  reliability: 'MEDIUM',
  reliability_label_fr: 'Moyenne',
  unavailable_fr: {
    cout: 'Aucun tarif de l’eau n’est renseigné pour cette parcelle.',
  },
}

export const recommendation: IrrigationRecommendation = {
  field_code: 'P03',
  field_name_fr: 'Verger agrumes Est',
  recommendation: 'IRRIGATE',
  recommendation_label_fr: 'Irrigation recommandée',
  headline_fr: decision.headline_fr,
  water_volume_m3: 84.2,
  net_requirement_mm: 12.4,
  duration_minutes: 130,
  duration_label_fr: '2 h 10',
  estimated_cost_mad: null,
  et0_mm_day: 5.83,
  etc_mm_day: 4.08,
  stress_level: 'moderate',
  stress_label_fr: 'Stress modéré',
  reliability: 'MEDIUM',
  reliability_label_fr: 'Moyenne',
  decision,
}

export const fields: Field[] = [
  {
    code: 'P03',
    name_fr: 'Verger agrumes Est',
    site_name_fr: 'Domaine Souss Verde',
    area_ha: 4.1,
    latitude: 30.42,
    longitude: -9.21,
    boundary_geojson: null,
    crop_code: 'CITRUS',
    crop_name_fr: HOSTILE_NAME,
    soil_name_fr: 'Limon',
    system_name_fr: 'Goutte-à-goutte',
    has_flow_rate: true,
    has_water_tariff: false,
    moisture: {
      value_pct: 18.4,
      recorded_at: '2026-09-08T06:00:00Z',
      state: 'SIMULATED',
      state_label_fr: 'Simulé',
      origin: 'SEED_DEMO',
      origin_label_fr: 'Jeu de démonstration',
    },
    blocked_reason_fr: null,
  },
  {
    code: 'P99',
    name_fr: 'Parcelle sans culture',
    site_name_fr: 'Domaine Souss Verde',
    area_ha: 1.0,
    latitude: 30.4,
    longitude: -9.2,
    boundary_geojson: null,
    crop_code: null,
    crop_name_fr: null,
    soil_name_fr: null,
    system_name_fr: null,
    has_flow_rate: false,
    has_water_tariff: false,
    moisture: null,
    blocked_reason_fr: 'Aucune culture renseignée pour cette parcelle.',
  },
]

export const shipment: Shipment = {
  reference: 'EXP-1842',
  product_name_fr: HOSTILE_NAME,
  volume_tonnes: 180,
  transport_mode: 'REFRIGERATED_TRUCK',
  transport_mode_label_fr: 'Camion frigorifique',
  status: 'IN_TRANSIT',
  status_label_fr: 'En transit',
  origin_site_fr: 'Domaine Souss Verde',
  destination_site_fr: 'Client Casablanca',
  origin_latitude: 30.42,
  origin_longitude: -9.21,
  destination_latitude: 33.57,
  destination_longitude: -7.59,
  departure_at: '2026-09-09T05:00:00Z',
  sla_deadline_at: '2026-09-09T21:00:00Z',
  hours_to_deadline: 11.5,
  requires_cold_chain: true,
  source_field_code: 'P01',
  risk_analysis_fr: null,
}

export const shipmentRisk: ShipmentRisk = {
  reference: 'EXP-1842',
  headline_fr: 'Alternative 1 — via Safi, El Jadida pour 669 MAD de plus.',
  outcome_code: 'ALTERNATE_ROUTE',
  profile_fr: 'Denrée périssable',
  profile_rationale_fr:
    'Le risque et le respect de l’échéance pèsent plus que le coût.',
  risk_level: 'HIGH',
  risk_level_label_fr: 'Risque élevé',
  exposure_fraction: 0.354,
  exposed_distance_km: 192,
  disruption_indicator: 0.58,
  disruption_caveat_fr:
    'Indicateur comparatif dérivé de règles explicites, destiné à classer des ' +
    'itinéraires entre eux. Ce n’est pas une probabilité : aucun historique ' +
    'd’incidents marocains ne l’a calibré.',
  departure_at: '2026-09-10T00:20:00Z',
  sla_deadline_at: '2026-09-10T20:00:00Z',
  sla_compliant: true,
  exposed_segments: [
    {
      from_name_fr: 'Imi n’Tanoute',
      to_name_fr: 'Chichaoua',
      road_ref: 'A7',
      distance_km: 42,
      hours_from_departure: 1.75,
      entry_at: '2026-09-10T02:04:00Z',
      exit_at: '2026-09-10T02:28:00Z',
      risk_level: 'CRITICAL',
      risk_level_label_fr: 'Risque critique',
      reasons_fr: [
        'Cumul de pluie sur 24 h avant passage : 140,0 mm lors du passage prévu ' +
          'entre 10/09 02:04 et 02:28 (seuil de vigilance 30 mm).',
      ],
      latitudes: [31.17, 31.54],
      longitudes: [-8.85, -8.76],
    },
  ],
  alternatives: [
    {
      id: 'itineraire-1',
      label_fr: 'Alternative 1 — via Safi, El Jadida',
      description_fr: 'Corridor différent, départ inchangé (542 km).',
      kind: 'ALTERNATE_ROUTE',
      is_current_plan: false,
      is_feasible: true,
      rank: 1,
      is_recommended: true,
      cost_mad: 62195,
      cost_delta_mad: 669,
      duration_hours: 7.21,
      duration_delta_hours: 1.52,
      departure_at: '2026-09-10T00:20:00Z',
      arrival_at: '2026-09-10T07:33:00Z',
      sla_margin_hours: 12.8,
      risk_level: 'LOW',
      risk_level_label_fr: 'Risque faible',
      risk_delta: -0.624,
      exposure_fraction: 0,
      rejection_reasons_fr: [],
      path_lonlat: [
        [-9.6, 30.43],
        [-9.24, 32.3],
        [-7.59, 33.57],
      ],
    },
    {
      id: 'plan-actuel',
      label_fr: 'Plan actuel',
      description_fr: 'Itinéraire prévu Agadir → Casablanca, départ inchangé.',
      kind: 'CURRENT_PLAN',
      is_current_plan: true,
      is_feasible: true,
      rank: 5,
      is_recommended: false,
      cost_mad: 61526,
      cost_delta_mad: 0,
      duration_hours: 5.69,
      duration_delta_hours: 0,
      departure_at: '2026-09-10T00:20:00Z',
      arrival_at: '2026-09-10T06:01:00Z',
      sla_margin_hours: 14.3,
      risk_level: 'HIGH',
      risk_level_label_fr: 'Risque élevé',
      risk_delta: 0,
      exposure_fraction: 0.354,
      rejection_reasons_fr: [],
      path_lonlat: [
        [-9.6, 30.43],
        [-7.98, 31.63],
        [-7.59, 33.57],
      ],
    },
    {
      id: 'depart-avance-10h',
      label_fr: 'Avancer le départ de 10 h',
      description_fr: 'Départ à 09/09 14:20, avant le délai de préparation minimal.',
      kind: 'DEPARTURE_SHIFT',
      is_current_plan: false,
      is_feasible: false,
      rank: null,
      is_recommended: false,
      cost_mad: null,
      cost_delta_mad: null,
      duration_hours: null,
      duration_delta_hours: null,
      departure_at: null,
      arrival_at: null,
      sla_margin_hours: null,
      risk_level: null,
      risk_level_label_fr: null,
      risk_delta: null,
      exposure_fraction: null,
      rejection_reasons_fr: [
        'Départ trop proche : un minimum de 3 h est nécessaire pour préparer et ' +
          'charger l’expédition.',
      ],
      path_lonlat: [],
    },
  ],
  reliability: 'LOW',
  reliability_label_fr: 'Faible',
  decision,
}
